import Circle.Core.Period
import Mathlib.GroupTheory.Coset.Card

namespace Circle

/-- The additive subgroup generated by a stride. Its cosets are the stride-orbit classes. -/
noncomputable def orbitSubgroup (n k : Nat) : AddSubgroup (C n) :=
  AddSubgroup.zmultiples (stride n k)

/-- The quotient whose elements are stride-orbit classes on `C n`. -/
abbrev orbitClassQuotient (n k : Nat) :=
  (C n) ⧸ orbitSubgroup n k

/-- Two nodes are in the same stride-orbit class when they agree in the orbit quotient. -/
noncomputable def sameOrbit (n k : Nat) (x y : C n) : Prop :=
  QuotientAddGroup.mk' (orbitSubgroup n k) x =
    QuotientAddGroup.mk' (orbitSubgroup n k) y

/-- Same-orbit equality is exactly difference membership in the stride-generated subgroup. -/
theorem sameOrbit_iff_difference_mem_orbitSubgroup (n k : Nat) (x y : C n) :
    sameOrbit n k x y ↔ x - y ∈ orbitSubgroup n k := by
  unfold sameOrbit
  simpa using
    (QuotientAddGroup.eq_iff_sub_mem (N := orbitSubgroup n k) (x := x) (y := y))

/-- Same-orbit natural representatives are congruent modulo `gcd(n,k)`. -/
theorem sameOrbit_nat_modEq_gcd_of_sameOrbit
    (n k x y : Nat)
    (h : sameOrbit n k ((x : Nat) : C n) ((y : Nat) : C n)) :
    x ≡ y [MOD Nat.gcd n k] := by
  let g := Nat.gcd n k
  let φ := ZMod.castHom (Nat.gcd_dvd_left n k) (ZMod g)
  have hmem :
      ((x : Nat) : C n) - ((y : Nat) : C n) ∈ orbitSubgroup n k :=
    (sameOrbit_iff_difference_mem_orbitSubgroup n k
      ((x : Nat) : C n) ((y : Nat) : C n)).mp h
  have hzero :
      φ (((x : Nat) : C n) - ((y : Nat) : C n)) = 0 := by
    unfold orbitSubgroup at hmem
    rcases (AddSubgroup.mem_zmultiples_iff.mp hmem) with ⟨z, hz⟩
    rw [← hz]
    have hstride_zero : φ (stride n k) = 0 := by
      unfold φ stride
      rw [ZMod.castHom_apply]
      rw [ZMod.cast_natCast (Nat.gcd_dvd_left n k)]
      exact (CharP.cast_eq_zero_iff (ZMod g) g k).mpr
        (by simpa [g] using Nat.gcd_dvd_right n k)
    simp [hstride_zero]
  have hcast : ((x : Nat) : ZMod g) = ((y : Nat) : ZMod g) := by
    have hzero' :
        (ZMod.cast (((x : Nat) : C n) - ((y : Nat) : C n)) : ZMod g) = 0 := by
      simpa [φ, g] using hzero
    have hsub :
        ((x : Nat) : ZMod g) - ((y : Nat) : ZMod g) = 0 := by
      rw [ZMod.cast_sub (Nat.gcd_dvd_left n k)] at hzero'
      rw [ZMod.cast_natCast (Nat.gcd_dvd_left n k)] at hzero'
      rw [ZMod.cast_natCast (Nat.gcd_dvd_left n k)] at hzero'
      exact hzero'
    exact sub_eq_zero.mp hsub
  exact (ZMod.natCast_eq_natCast_iff x y g).mp hcast

/-- The number of stride-orbit classes on `C n`. -/
noncomputable def orbitClassCount (n k : Nat) : Nat :=
  Nat.card (orbitClassQuotient n k)

theorem orbit_decomposition_count {n k : Nat} (hn : n ≠ 0) :
    orbitClassCount n k = Nat.gcd n k := by
  haveI : NeZero n := ⟨hn⟩
  let H : AddSubgroup (C n) := orbitSubgroup n k
  have hHcard : Nat.card H = n / Nat.gcd n k := by
    calc
      Nat.card H = Fintype.card (AddSubgroup.zmultiples (stride n k)) := by
        dsimp [H, orbitSubgroup]
        rw [Nat.card_eq_fintype_card]
      _ = addOrderOf (stride n k) :=
        Fintype.card_zmultiples (G := C n) (x := stride n k)
      _ = n / Nat.gcd n k := by
        unfold stride
        simpa using ZMod.addOrderOf_coe k (n := n) hn
  have hlag : orbitClassCount n k * Nat.card H = Nat.card (C n) := by
    dsimp [orbitClassCount, orbitClassQuotient]
    simpa [H] using (AddSubgroup.card_eq_card_quotient_mul_card_addSubgroup H).symm
  have hlag' : orbitClassCount n k * (n / Nat.gcd n k) = n := by
    simpa [hHcard, Nat.card_zmod] using hlag
  have hgpos : 0 < Nat.gcd n k := Nat.gcd_pos_of_pos_left k (Nat.pos_of_ne_zero hn)
  have hqpos : 0 < n / Nat.gcd n k :=
    Nat.div_pos (Nat.gcd_le_left k (Nat.pos_of_ne_zero hn)) hgpos
  have hg_mul_q : Nat.gcd n k * (n / Nat.gcd n k) = n := by
    rw [Nat.mul_comm]
    exact Nat.div_mul_cancel (Nat.gcd_dvd_left n k)
  exact Nat.mul_right_cancel hqpos (hlag'.trans hg_mul_q.symm)

end Circle
