import Circle.Applications.CircleAI
import Circle.Applications.CircleTransformer

/-!
AI 2 sidecar.

This file re-exports the cyclic memory-slot seed used by
`papers/applications/PAPER_AI_02_COIL_ATTENTION_AND_MEMORY.md`.
-/

namespace Circle.PaperAI02

#check Circle.Applications.memorySlot
#check Circle.Applications.memorySlot_lt_bankSize
#check Circle.Applications.memorySlot_add_bankSize
#check Circle.Applications.memorySlot_add_mul_bankSize
#check Circle.Applications.memorySlot_idempotent
#check Circle.Applications.memorySlot_zero
#check Circle.Applications.kvCacheSlot
#check Circle.Applications.kvCacheSlotCollision
#check Circle.Applications.kvCacheWindowContains
#check Circle.Applications.kvCacheSlot_lt_cacheSize
#check Circle.Applications.kvCacheSlot_add_cacheSize
#check Circle.Applications.kvCacheSlotCollision_iff_gap_dvd
#check Circle.Applications.kvCacheSlot_ne_of_positive_gap_lt_cache
#check Circle.Applications.kvCacheWindow_nextOverwrite_after_current
#check Circle.Applications.loopRequiredSteps_pos
#check Circle.Applications.loopRequiredSteps_le_loopPeriod
#check Circle.Applications.loopRequiredSteps_add_loopPeriod
#check Circle.Applications.loopRequiredSteps_add_mul_loopPeriod
#check Circle.Applications.tokenRecurrenceBudget_add_loopPeriod
#check Circle.Applications.tokenRecurrenceBudget_add_mul_loopPeriod
#check Circle.Applications.tokenRecurrenceBudget_le_loopPeriod
#check Circle.Applications.tokenRecurrenceBudget_zero
#check Circle.Applications.loopedRecurrentState_lt_period
#check Circle.Applications.loopedRecurrentState_one_zero
#check Circle.Applications.loopedRecurrentState_of_requiredSteps
#check Circle.Applications.loopedRecurrentState_of_tokenRecurrenceBudget
#check Circle.Applications.loopedRecurrentState_tokenBudget_add_mul_loopPeriod
#check Circle.Applications.loopedRecurrentState_budget_add_period
#check Circle.Applications.loopedRecurrentState_budget_add_mul_period
#check Circle.Applications.tokenActiveAtStep_one
#check Circle.Applications.tokenActiveAtStep_add_mul_loopPeriod
#check Circle.Applications.tokenActiveAtStep_step_le_loopPeriod
#check Circle.Applications.tokenInactiveAtStep_of_loopPeriod_lt_step
#check Circle.Applications.middleBlockRoute_ge_start
#check Circle.Applications.middleBlockRoute_lt_stop
#check Circle.Applications.middleBlockRoute_add_width
#check Circle.Applications.middleBlockRoute_add_mul_width
#check Circle.Applications.middleBlockRoute_zero
#check Circle.Applications.middleBlockBudgetRoute_block_ge_start
#check Circle.Applications.middleBlockBudgetRoute_block_lt_stop
#check Circle.Applications.middleBlockBudgetRoute_budget_pos
#check Circle.Applications.middleBlockBudgetRoute_budget_le_loopPeriod
#check Circle.Applications.middleBlockBudgetRoute_add_commonCycle
#check Circle.Applications.middleBlockBudgetRoute_add_mul_commonCycle
#check Circle.Applications.middleBlockBudgetRoute_zero
#check Circle.Applications.trainingFreeLoopBudget_le_maxLoops
#check Circle.Applications.trainingFreeLoopBudget_le_requiredSteps
#check Circle.Applications.trainingFreeLoopBudget_add_loopPeriod
#check Circle.Applications.trainingFreeLoopBudget_add_mul_loopPeriod
#check Circle.Applications.trainingFreeLoopBudget_eq_required_of_available
#check Circle.Applications.loopOverthinkingBoundary_ge_required
#check Circle.Applications.loopOverthinkingBoundary_add_loopPeriod
#check Circle.Applications.loopOverthinkingBoundary_add_mul_loopPeriod
#check Circle.Applications.loopExitAvailable_of_loopPeriod_le_budget
#check Circle.Applications.loopExitAvailable_add_loopPeriod
#check Circle.Applications.loopExitAvailable_add_mul_loopPeriod
#check Circle.Applications.loopExitCertificate_exit_eq_required
#check Circle.Applications.loopExitCertificate_within_budget
#check Circle.Applications.loopExitCertificate_within_guardrail
#check Circle.Applications.loopExitCertificate_exit_available
#check Circle.Applications.loopExitCertificate_budget_eq_exitStep
#check Circle.Applications.loopExitCertificate_exitStep_add_mul_loopPeriod
#check Circle.Applications.loopExitCertificate_boundary_add_mul_loopPeriod
#check Circle.Applications.localLagReach
#check Circle.Applications.coilLagReach
#check Circle.Applications.hybridLagReach
#check Circle.Applications.localLagReach_of_le
#check Circle.Applications.coilLagReach_of_step
#check Circle.Applications.coilLagReach_add_context
#check Circle.Applications.coilStrideFamilyLagReach
#check Circle.Applications.hybridFamilyLagReach
#check Circle.Applications.coilStrideFamilyLagReach_of_member_step
#check Circle.Applications.coilStrideFamilyLagReach_add_context
#check Circle.Applications.hybridLagReach_of_local
#check Circle.Applications.hybridLagReach_of_coil
#check Circle.Applications.hybridFamilyLagReach_of_local
#check Circle.Applications.hybridFamilyLagReach_of_family
#check Circle.Applications.hybridFamilyLagReach_of_member_step
#check Circle.Applications.hybridFamilyLagGap_iff_not_local_and_not_family
#check Circle.Applications.hybridFamilyLagGap_of_above_window_and_forall_stride_step_ne

end Circle.PaperAI02
