"""Python reference models for Circle Calculus.

These models support examples and tests. They are not formal proofs.
"""

from .finite import Circle
from .core import (
    finite_circle,
    finite_orbit,
    finite_orbit_decomposition,
    finite_period,
    is_full_coil,
)
from .additive import (
    CauchyDavenportExample,
    cauchy_davenport_example,
    circle_pair_sum_counts,
    circle_sumset,
    egz_sharpness_family,
    has_zero_sum_subsequence,
    zero_sum_subsequence_witnesses,
)
from .finite_search import (
    FiniteCoilSignature,
    build_s1_signature_index,
    finite_coil_signature,
    search_theorems_by_tags,
    signature_tags,
)
from .extremal import (
    CycleCirculantExample,
    EKRStarExample,
    HomotheticCopy,
    MonochromaticProgression,
    PrefixDensityExample,
    RothIntervalExample,
    all_binary_colorings_have_3ap,
    circulant_edges,
    cycle_circulant_example,
    cycle_graph_edges,
    ekr_star_example,
    ekr_star_family,
    find_monochromatic_arithmetic_progression,
    find_monochromatic_combinatorial_line,
    find_monochromatic_homothetic_copy,
    is_intersecting_family,
    is_three_ap_free,
    is_uniform_family,
    katona_prefixed_density_example,
    regular_polygon_unit_embedding,
    roth_interval_example,
    three_ap_witnesses,
)
from .number_provenance import (
    NumberProvenance,
    StrideProvenance,
    divisors,
    factor_pairs,
    number_provenance,
    provenance_summary,
    stride_provenance,
    value_only_summary,
)

__all__ = [
    "Circle",
    "CauchyDavenportExample",
    "CycleCirculantExample",
    "EKRStarExample",
    "FiniteCoilSignature",
    "HomotheticCopy",
    "MonochromaticProgression",
    "NumberProvenance",
    "PrefixDensityExample",
    "RothIntervalExample",
    "StrideProvenance",
    "all_binary_colorings_have_3ap",
    "build_s1_signature_index",
    "cauchy_davenport_example",
    "circulant_edges",
    "cycle_circulant_example",
    "cycle_graph_edges",
    "circle_pair_sum_counts",
    "circle_sumset",
    "divisors",
    "ekr_star_example",
    "ekr_star_family",
    "egz_sharpness_family",
    "factor_pairs",
    "finite_circle",
    "finite_coil_signature",
    "finite_orbit",
    "finite_orbit_decomposition",
    "finite_period",
    "find_monochromatic_arithmetic_progression",
    "find_monochromatic_combinatorial_line",
    "find_monochromatic_homothetic_copy",
    "has_zero_sum_subsequence",
    "is_intersecting_family",
    "is_full_coil",
    "is_three_ap_free",
    "is_uniform_family",
    "katona_prefixed_density_example",
    "number_provenance",
    "provenance_summary",
    "regular_polygon_unit_embedding",
    "roth_interval_example",
    "search_theorems_by_tags",
    "signature_tags",
    "stride_provenance",
    "three_ap_witnesses",
    "value_only_summary",
    "zero_sum_subsequence_witnesses",
]
