"""Stable public API for building Circle AI contract fixtures.

The records produced here are finite structural contracts. They cite Lean
theorem ids and carry explicit non-claim boundaries; they are not benchmark or
model-quality results.
"""

from __future__ import annotations

from .applications.circle_ai_contract_runner import (
    SUPPORTED_CONTRACT_KINDS,
    build_architecture_config_certification_bundle,
    build_circulant_block_cyclic_mixer_receipt,
    build_contract_certification_bundle,
    build_contract_certification_bundle_json_schema,
    build_contract_receipt,
    build_contract_receipt_from_request,
    build_contract_request,
    build_contract_request_from_architecture_config,
    build_contract_runner_check_report,
    build_contract_runner_check_json_schema,
    build_cyclic_memory_receipt,
    build_kv_cache_receipt,
    build_multicoil_phase_feature_receipt,
    build_recurrence_receipt,
    build_rope_contract_request_from_model_config,
    build_rope_model_config_certification_bundle,
    build_rope_model_config_import_report,
    build_rope_request_parameters_from_model_config,
    build_rope_receipt,
    build_seed_rule_receipt,
    build_sparse_attention_receipt,
    build_strided_candidate_fanout_receipt,
    build_architecture_config_import_report,
    build_architecture_config_import_json_schema,
    build_validated_contract_receipt,
    build_validated_contract_receipt_from_architecture_config,
    build_validated_contract_receipt_from_request,
    build_validated_rope_receipt_from_model_config,
    canonical_contract_kind,
    receipt_summary_lines,
)
from .applications.circle_ai_contracts import (
    SCHEMA_ID as CONTRACT_PACK_SCHEMA_ID,
    build_circulant_block_cyclic_mixer_contract,
    build_contract_pack,
    build_cyclic_memory_contract,
    build_multicoil_phase_feature_contract,
    build_recurrence_schedule_contract,
    build_seed_rule_contract,
    build_strided_candidate_fanout_contract,
)
from .circle_graph_coverage import (
    CIRCLE_GRAPH_COVERAGE_CLAIM_BOUNDARY,
    CIRCLE_GRAPH_COVERAGE_LEAN_DECLARATIONS,
    CIRCLE_GRAPH_COVERAGE_SCHEMA_ID,
    CIRCLE_GRAPH_COVERAGE_THEOREM_IDS,
    CircleGraphCoverageReport,
    circle_graph_coverage_report,
    circle_graph_directed_edges,
    circle_graph_lag_generators,
)
from .position_phase import (
    POSITION_PHASE_CLAIM_BOUNDARY,
    POSITION_PHASE_COLLISION_REPORT_SCHEMA_ID,
    POSITION_PHASE_GRID_REPORT_SCHEMA_ID,
    POSITION_PHASE_LEAN_DECLARATIONS,
    POSITION_PHASE_SCHEMA_ID,
    POSITION_PHASE_THEOREM_IDS,
    PhaseBank,
    PhaseBankCollisionReport,
    PhaseChannel,
    PhaseChannelCollisionResult,
    PhaseGrid2DCollisionReport,
    longrope_nonuniform_scaled_phase_bank,
    period_divides_gap,
    phase_bank_collision_report,
    phase_bank_from_periods,
    phase_channel_collides,
    phase_channel_distinguishes,
    phase_grid_2d_collision_report,
    phase_residue,
    rope_integer_phase_bank,
    scaled_periods,
    scaled_phase_bank,
    sinusoidal_integer_phase_bank,
    xpos_integer_phase_bank,
    yarn_uniform_scaled_phase_bank,
)


__all__ = [
    "CONTRACT_PACK_SCHEMA_ID",
    "CIRCLE_GRAPH_COVERAGE_CLAIM_BOUNDARY",
    "CIRCLE_GRAPH_COVERAGE_LEAN_DECLARATIONS",
    "CIRCLE_GRAPH_COVERAGE_SCHEMA_ID",
    "CIRCLE_GRAPH_COVERAGE_THEOREM_IDS",
    "CircleGraphCoverageReport",
    "POSITION_PHASE_CLAIM_BOUNDARY",
    "POSITION_PHASE_COLLISION_REPORT_SCHEMA_ID",
    "POSITION_PHASE_GRID_REPORT_SCHEMA_ID",
    "POSITION_PHASE_LEAN_DECLARATIONS",
    "POSITION_PHASE_SCHEMA_ID",
    "POSITION_PHASE_THEOREM_IDS",
    "PhaseBank",
    "PhaseBankCollisionReport",
    "PhaseChannel",
    "PhaseChannelCollisionResult",
    "PhaseGrid2DCollisionReport",
    "SUPPORTED_CONTRACT_KINDS",
    "build_architecture_config_certification_bundle",
    "build_circulant_block_cyclic_mixer_contract",
    "build_circulant_block_cyclic_mixer_receipt",
    "build_contract_certification_bundle",
    "build_contract_certification_bundle_json_schema",
    "build_contract_pack",
    "build_contract_receipt",
    "build_contract_receipt_from_request",
    "build_contract_request",
    "build_contract_request_from_architecture_config",
    "build_contract_runner_check_report",
    "build_contract_runner_check_json_schema",
    "build_cyclic_memory_contract",
    "build_cyclic_memory_receipt",
    "build_kv_cache_receipt",
    "build_multicoil_phase_feature_contract",
    "build_multicoil_phase_feature_receipt",
    "build_recurrence_receipt",
    "build_recurrence_schedule_contract",
    "build_rope_contract_request_from_model_config",
    "build_rope_model_config_certification_bundle",
    "build_rope_model_config_import_report",
    "build_rope_request_parameters_from_model_config",
    "build_rope_receipt",
    "build_seed_rule_contract",
    "build_seed_rule_receipt",
    "build_sparse_attention_receipt",
    "build_strided_candidate_fanout_contract",
    "build_strided_candidate_fanout_receipt",
    "build_architecture_config_import_report",
    "build_architecture_config_import_json_schema",
    "build_validated_contract_receipt",
    "build_validated_contract_receipt_from_architecture_config",
    "build_validated_contract_receipt_from_request",
    "build_validated_rope_receipt_from_model_config",
    "canonical_contract_kind",
    "circle_graph_coverage_report",
    "circle_graph_directed_edges",
    "circle_graph_lag_generators",
    "longrope_nonuniform_scaled_phase_bank",
    "period_divides_gap",
    "phase_bank_collision_report",
    "phase_bank_from_periods",
    "phase_channel_collides",
    "phase_channel_distinguishes",
    "phase_grid_2d_collision_report",
    "phase_residue",
    "receipt_summary_lines",
    "rope_integer_phase_bank",
    "scaled_periods",
    "scaled_phase_bank",
    "sinusoidal_integer_phase_bank",
    "xpos_integer_phase_bank",
    "yarn_uniform_scaled_phase_bank",
]
