"""Stable public API for finite Circle Calculus.

This module is intentionally small. It exposes the finite-circle and winding
helpers that downstream projects can rely on without importing the larger
research/application namespaces.
"""

from __future__ import annotations

from .finite import Circle
from .harmonics import (
    SpectralConvolutionReport,
    character_value,
    circular_convolution,
    circulant_matrix,
    dft_matrix,
    finite_fourier_coefficients,
    inverse_finite_fourier,
    root_of_unity,
    spectral_aliasing_report,
    spectral_convolution_report,
)
from .number_provenance import (
    NumberProvenance,
    StrideProvenance,
    divisors,
    factor_pairs,
    number_provenance,
    provenance_summary,
    stride_provenance,
    value_only_summary,
)
from .winding import LiftedNode, lift, lift_add, lift_iter_successor, lift_successor


def finite_circle(size: int) -> Circle:
    """Return the finite cyclic address space with ``size`` nodes."""
    return Circle(size)


def finite_orbit(size: int, stride: int, start: int = 0) -> list[int]:
    """Return the orbit generated by repeatedly adding ``stride`` modulo ``size``."""
    return Circle(size).orbit(start, stride)


def finite_period(size: int, stride: int) -> int:
    """Return the period of ``stride`` on the finite circle of ``size`` nodes."""
    return Circle(size).period(stride)


def finite_orbit_decomposition(size: int, stride: int) -> list[list[int]]:
    """Return all stride orbits on the finite circle of ``size`` nodes."""
    return Circle(size).orbit_decomposition(stride)


def is_full_coil(size: int, stride: int) -> bool:
    """Return whether ``stride`` visits every node before closing."""
    return Circle(size).is_full_coil(stride)


__all__ = [
    "Circle",
    "LiftedNode",
    "NumberProvenance",
    "SpectralConvolutionReport",
    "StrideProvenance",
    "character_value",
    "circular_convolution",
    "circulant_matrix",
    "dft_matrix",
    "divisors",
    "factor_pairs",
    "finite_fourier_coefficients",
    "finite_circle",
    "finite_orbit",
    "finite_orbit_decomposition",
    "finite_period",
    "inverse_finite_fourier",
    "is_full_coil",
    "lift",
    "lift_add",
    "lift_iter_successor",
    "lift_successor",
    "number_provenance",
    "provenance_summary",
    "root_of_unity",
    "spectral_aliasing_report",
    "spectral_convolution_report",
    "stride_provenance",
    "value_only_summary",
]
