"""Stable public API for finite Circle Calculus.

This module is intentionally small. It exposes the finite-circle and winding
helpers that downstream projects can rely on without importing the larger
research/application namespaces.
"""

from __future__ import annotations

from .finite import Circle
from .circular_statistics import (
    CIRCULAR_STATISTICS_CLAIM_BOUNDARY,
    CIRCULAR_STATISTICS_LEAN_DECLARATIONS,
    CIRCULAR_STATISTICS_SCHEMA_ID,
    CIRCULAR_STATISTICS_THEOREM_IDS,
    CircularMeanReport,
    angular_difference,
    circular_mean,
    circular_mean_report,
    circular_variance,
    finite_residue_histogram,
    finite_residue_samples,
    finite_same_phase,
    finite_wrapped_distance,
    mean_resultant_length,
    normalize_angle,
    resultant_vector,
    von_mises_weight,
    wrapped_angular_error,
)
from .equivariance import (
    CYCLIC_EQUIVARIANCE_CLAIM_BOUNDARY,
    CYCLIC_EQUIVARIANCE_LEAN_DECLARATIONS,
    CYCLIC_EQUIVARIANCE_SCHEMA_ID,
    CYCLIC_EQUIVARIANCE_THEOREM_IDS,
    EquivarianceCheckReport,
    check_cyclic_equivariance,
    circulant_equivariance_report,
    circulant_layer,
    cyclic_orbit,
    cyclic_shift,
    cyclic_sum,
    cyclic_sum_invariance_report,
    dihedral_orbit,
    dihedral_transform,
    reflect_signal,
)
from .harmonics import (
    SpectralConvolutionReport,
    character_value,
    circular_convolution,
    circulant_matrix,
    dft_matrix,
    finite_fourier_coefficients,
    inverse_finite_fourier,
    root_of_unity,
    spectral_aliasing_report,
    spectral_convolution_report,
)
from .number_provenance import (
    NumberProvenance,
    StrideProvenance,
    divisors,
    factor_pairs,
    number_provenance,
    provenance_summary,
    stride_provenance,
    value_only_summary,
)
from .phase_loop import (
    PHASE_LOOP_CLAIM_BOUNDARY,
    PHASE_LOOP_LEAN_DECLARATIONS,
    PHASE_LOOP_SCHEMA_ID,
    PHASE_LOOP_THEOREM_IDS,
    PhaseLockReport,
    PhaseLoopReport,
    finite_phase_gap,
    finite_phase_locked,
    loop_gauge_shifted_charge,
    loop_winding_lift,
    normalize_phase_increments,
    phase_lock_report,
    phase_loop_charge,
    phase_loop_report,
    reverse_phase_increments,
    vortex_charge,
    winding_residue_reconstruct,
)
from .winding import LiftedNode, lift, lift_add, lift_iter_successor, lift_successor


def finite_circle(size: int) -> Circle:
    """Return the finite cyclic address space with ``size`` nodes."""
    return Circle(size)


def finite_orbit(size: int, stride: int, start: int = 0) -> list[int]:
    """Return the orbit generated by repeatedly adding ``stride`` modulo ``size``."""
    return Circle(size).orbit(start, stride)


def finite_period(size: int, stride: int) -> int:
    """Return the period of ``stride`` on the finite circle of ``size`` nodes."""
    return Circle(size).period(stride)


def finite_orbit_decomposition(size: int, stride: int) -> list[list[int]]:
    """Return all stride orbits on the finite circle of ``size`` nodes."""
    return Circle(size).orbit_decomposition(stride)


def is_full_coil(size: int, stride: int) -> bool:
    """Return whether ``stride`` visits every node before closing."""
    return Circle(size).is_full_coil(stride)


__all__ = [
    "CIRCULAR_STATISTICS_CLAIM_BOUNDARY",
    "CIRCULAR_STATISTICS_LEAN_DECLARATIONS",
    "CIRCULAR_STATISTICS_SCHEMA_ID",
    "CIRCULAR_STATISTICS_THEOREM_IDS",
    "CYCLIC_EQUIVARIANCE_CLAIM_BOUNDARY",
    "CYCLIC_EQUIVARIANCE_LEAN_DECLARATIONS",
    "CYCLIC_EQUIVARIANCE_SCHEMA_ID",
    "CYCLIC_EQUIVARIANCE_THEOREM_IDS",
    "Circle",
    "CircularMeanReport",
    "EquivarianceCheckReport",
    "LiftedNode",
    "NumberProvenance",
    "PHASE_LOOP_CLAIM_BOUNDARY",
    "PHASE_LOOP_LEAN_DECLARATIONS",
    "PHASE_LOOP_SCHEMA_ID",
    "PHASE_LOOP_THEOREM_IDS",
    "PhaseLockReport",
    "PhaseLoopReport",
    "SpectralConvolutionReport",
    "StrideProvenance",
    "angular_difference",
    "character_value",
    "check_cyclic_equivariance",
    "circular_mean",
    "circular_mean_report",
    "circular_variance",
    "circular_convolution",
    "circulant_equivariance_report",
    "circulant_layer",
    "circulant_matrix",
    "cyclic_orbit",
    "cyclic_shift",
    "cyclic_sum",
    "cyclic_sum_invariance_report",
    "dft_matrix",
    "dihedral_orbit",
    "dihedral_transform",
    "divisors",
    "factor_pairs",
    "finite_fourier_coefficients",
    "finite_circle",
    "finite_orbit",
    "finite_orbit_decomposition",
    "finite_period",
    "finite_phase_gap",
    "finite_phase_locked",
    "finite_residue_histogram",
    "finite_residue_samples",
    "finite_same_phase",
    "finite_wrapped_distance",
    "inverse_finite_fourier",
    "is_full_coil",
    "lift",
    "lift_add",
    "lift_iter_successor",
    "lift_successor",
    "loop_gauge_shifted_charge",
    "loop_winding_lift",
    "mean_resultant_length",
    "normalize_angle",
    "normalize_phase_increments",
    "number_provenance",
    "phase_lock_report",
    "phase_loop_charge",
    "phase_loop_report",
    "provenance_summary",
    "reflect_signal",
    "reverse_phase_increments",
    "resultant_vector",
    "root_of_unity",
    "spectral_aliasing_report",
    "spectral_convolution_report",
    "stride_provenance",
    "value_only_summary",
    "von_mises_weight",
    "vortex_charge",
    "wrapped_angular_error",
    "winding_residue_reconstruct",
]
