import Circle.Applications.Circulant

/-!
# Finite cyclic and dihedral equivariance contracts

This module packages the existing cyclic-shift and circulant-convolution facts
as a public equivariance vocabulary. It also adds a minimal finite dihedral
interface: reflection of a signal, reflection involution, and the interaction
between reflection and cyclic shifts.

The proved claims are finite algebraic contracts. They do not assert image
model quality, steerable-kernel completeness, robustness, or continuous
rotation equivariance.
-/

namespace Circle.Applications

variable {n : Nat} {R A : Type*}

/-- Public name for the finite cyclic shift action on signals. -/
abbrev cyclicShift (s : ZMod n) (x : ZMod n → R) : ZMod n → R :=
  shiftBy s x

/-- A signal map is cyclic-equivariant when it commutes with every cyclic
shift. -/
def CyclicEquivariant
    (f : (ZMod n → R) → (ZMod n → R)) : Prop :=
  ∀ s x, f (cyclicShift s x) = cyclicShift s (f x)

/-- A readout is cyclic-invariant when shifting the signal does not change the
readout value. -/
def CyclicInvariant
    (readout : (ZMod n → R) → A) : Prop :=
  ∀ s x, readout (cyclicShift s x) = readout x

/-- A zero cyclic shift is the identity. -/
theorem cyclicShift_zero (x : ZMod n → R) :
    cyclicShift (0 : ZMod n) x = x := by
  exact shiftBy_zero x

/-- Cyclic shifts compose additively. -/
theorem cyclicShift_add (s t : ZMod n) (x : ZMod n → R) :
    cyclicShift (s + t) x = cyclicShift s (cyclicShift t x) := by
  exact shiftBy_add s t x

/-- The identity map is cyclic-equivariant. -/
theorem cyclicEquivariant_identity :
    CyclicEquivariant (n := n) (R := R) (fun x => x) := by
  intro _s _x
  rfl

/-- Cyclic-equivariant maps are closed under composition. -/
theorem cyclicEquivariant_comp
    {f g : (ZMod n → R) → (ZMod n → R)}
    (hf : CyclicEquivariant f) (hg : CyclicEquivariant g) :
    CyclicEquivariant (fun x => f (g x)) := by
  intro s x
  change f (g (cyclicShift s x)) = cyclicShift s (f (g x))
  rw [hg s x]
  exact hf s (g x)

/-- Pointwise sums of cyclic-equivariant maps are cyclic-equivariant. -/
theorem cyclicEquivariant_add
    [Add R] {f g : (ZMod n → R) → (ZMod n → R)}
    (hf : CyclicEquivariant f) (hg : CyclicEquivariant g) :
    CyclicEquivariant (fun x => f x + g x) := by
  intro s x
  change f (cyclicShift s x) + g (cyclicShift s x) =
    cyclicShift s (f x + g x)
  rw [hf s x, hg s x]
  funext i
  rfl

/-- Public functional form of a circulant convolution layer. -/
def circulantLayer [NeZero n] [CommRing R] (kernel : ZMod n → R) :
    (ZMod n → R) → (ZMod n → R) :=
  fun x => circConv kernel x

/-- Every circulant convolution layer is cyclic-equivariant. -/
theorem circulantLayer_cyclicEquivariant
    [NeZero n] [CommRing R]
    (kernel : ZMod n → R) :
    CyclicEquivariant (circulantLayer (n := n) kernel) := by
  intro s x
  exact circConv_shift_equivariant s kernel x

/-- Sum-pooling over the finite cyclic address space. -/
def cyclicSum [NeZero n] [AddCommMonoid R] (x : ZMod n → R) : R :=
  ∑ i : ZMod n, x i

/-- Sum-pooling is invariant under finite cyclic shifts. -/
theorem cyclicSum_shift_invariant
    [NeZero n] [AddCommMonoid R] (s : ZMod n) (x : ZMod n → R) :
    cyclicSum (cyclicShift s x) = cyclicSum x := by
  unfold cyclicSum cyclicShift shiftBy
  rw [← Equiv.sum_comp (Equiv.subRight s).symm]
  simp

/-! ### Minimal finite dihedral interface -/

/-- Reflect a signal by negating its finite circular index. -/
def reflectSignal (x : ZMod n → R) : ZMod n → R :=
  fun i => x (-i)

/-- Reflection is an involution. -/
theorem reflectSignal_involutive (x : ZMod n → R) :
    reflectSignal (reflectSignal x) = x := by
  funext i
  simp [reflectSignal]

/-- Reflection conjugates a shift by `s` into a shift by `-s`. -/
theorem reflectSignal_shift (s : ZMod n) (x : ZMod n → R) :
    reflectSignal (cyclicShift s x) =
      cyclicShift (-s) (reflectSignal x) := by
  funext i
  simp [reflectSignal, cyclicShift, shiftBy, sub_eq_add_neg, add_comm]

/-- Finite dihedral action generated by cyclic shifts and reflection. -/
def dihedralTransform
    (reflected : Bool) (s : ZMod n) (x : ZMod n → R) : ZMod n → R :=
  if reflected then cyclicShift s (reflectSignal x) else cyclicShift s x

/-- A signal map is dihedral-equivariant when it commutes with every finite
shift/reflection transform. -/
def DihedralEquivariant
    (f : (ZMod n → R) → (ZMod n → R)) : Prop :=
  ∀ reflected s x,
    f (dihedralTransform reflected s x) =
      dihedralTransform reflected s (f x)

/-- The identity map is dihedral-equivariant. -/
theorem dihedralEquivariant_identity :
    DihedralEquivariant (n := n) (R := R) (fun x => x) := by
  intro reflected _s _x
  cases reflected <;> rfl

/-- Dihedral equivariance contains cyclic equivariance as the no-reflection
case. -/
theorem dihedralEquivariant_implies_cyclic
    {f : (ZMod n → R) → (ZMod n → R)}
    (hf : DihedralEquivariant f) :
    CyclicEquivariant f := by
  intro s x
  simpa [dihedralTransform] using hf false s x

/-- The zero-shift reflection transform is an involution. -/
theorem dihedralTransform_reflection_zero_involutive
    (x : ZMod n → R) :
    dihedralTransform true (0 : ZMod n)
      (dihedralTransform true (0 : ZMod n) x) = x := by
  simp [dihedralTransform, reflectSignal_involutive]

end Circle.Applications
