import Circle.Generative.SeedRule

/-!
This sidecar imports the Lean source trail for the seed-rule provenance paper.
The checked declarations live in `Circle.Generative.SeedRule`; Python fixtures
remain executable references and do not prove minimality or compression
optimality.
-/

#check Circle.Generative.finiteCircleGenerator_regenerates_nodes
#check Circle.Generative.finiteCircleGenerator_generatedNodes_mem_iff_lt
#check Circle.Generative.finiteCircleGenerator_generatedNodes_nodup
#check Circle.Generative.finiteCircleGenerator_generatedNodes_zero
#check Circle.Generative.finiteCircleGenerator_generatedNodes_nonempty
#check Circle.Generative.coilOrbitGenerator_regenerates_orbit
#check Circle.Generative.orbitDecompositionGenerator_regenerates_orbits
#check Circle.Generative.orbitDecompositionGenerator_generatedOrbits_length
#check Circle.Generative.orbitDecompositionGenerator_generatedOrbitFor_length
#check Circle.Generative.orbitDecompositionGenerator_orbitCount_mul_period
#check Circle.Generative.orbitDecompositionGenerator_orbitCount_eq_orbitClassCount
#check Circle.Generative.orbitDecompositionGenerator_modRepresentative_lt_orbitCount
#check Circle.Generative.orbitDecompositionGenerator_modRepresentative_covers
#check Circle.Generative.orbitDecompositionGenerator_representatives_sameOrbit_iff_eq
#check Circle.Generative.orbitDecompositionGenerator_distinct_representatives_disjoint
#check Circle.Generative.proofGlyphGenerator_regenerates_certificate
#check Circle.Generative.generatorComparison_requires_exact_regeneration
#check Circle.Generative.generatorComparison_self_exact
#check Circle.Generative.generatorComparison_exact_regeneration_symm
#check Circle.Generative.generatorComparison_exact_regeneration_trans
#check Circle.Generative.generatorComparison_exact_regeneration_iff_fields_eq
#check Circle.Generative.generatorComparison_exact_regeneration_fields_eq
#check Circle.Generative.generatorComparison_not_exact_of_ne
#check Circle.Generative.emptyBoundedGeneratorSearch_candidateCount
#check Circle.Generative.emptyBoundedGeneratorSearch_exactCandidateCount
#check Circle.Generative.emptyBoundedGeneratorSearch_bestExact_none
#check Circle.Generative.singletonExactGeneratorSearch_candidateCount
#check Circle.Generative.singletonExactGeneratorSearch_exactCandidateCount
#check Circle.Generative.singletonExactGeneratorSearch_bestExact_some
#check Circle.Generative.singletonExactGeneratorSearch_bestExact_exact
#check Circle.Generative.boundedGeneratorSearch_bestExact_mem_exactCandidates
#check Circle.Generative.boundedGeneratorSearch_bestExact_mem_candidates
#check Circle.Generative.boundedGeneratorSearch_bestExact_exact
#check Circle.Generative.boundedGeneratorSearch_exactCandidate_mem_candidates
#check Circle.Generative.boundedGeneratorSearch_exactCandidate_exact
#check Circle.Generative.boundedGeneratorSearch_bestExact_none_iff_exactCandidates_empty
#check Circle.Generative.boundedGeneratorSearch_bestExact_none_iff_exactCandidateCount_zero
#check Circle.Generative.boundedGeneratorSearch_bestExact_some_exactCandidateCount_pos
#check Circle.Generative.boundedGeneratorSearch_exactCandidateCount_pos_iff_exists_bestExact
#check Circle.Generative.boundedGeneratorSearch_exactCandidateCount_le_candidateCount
#check Circle.Generative.boundedGeneratorSearch_bestExact_some_candidateCount_pos
#check Circle.Generative.singletonExactGeneratorSearch_bestExact_mem_exactCandidates
#check Circle.Generative.singletonExactGeneratorSearch_bestExact_mem_candidates
