import Circle.Applications.RoPECertifier

/-!
AI 4 sidecar: proof-carrying RoPE position distinguishability certifier.

The paper and CLI cite these declarations for the exact integer-period
discretized phase-bank contract.
-/

namespace Circle.PaperAI04

#check Circle.Applications.ropeDiscretePhase
#check Circle.Applications.ropeDiscreteCollision
#check Circle.Applications.ropeDiscreteDistinguishable
#check Circle.Applications.ropeDiscreteCollision_iff_gap_dvd
#check Circle.Applications.ropeDiscreteDistinguishable_iff_not_gap_dvd
#check Circle.Applications.ropeDiscreteCollision_iff_eq_on_context
#check Circle.Applications.ropePhaseBankCollision
#check Circle.Applications.ropePhaseBankDistinguishable
#check Circle.Applications.ropePhaseBankCollision_iff_forall_gap_dvd
#check Circle.Applications.ropePhaseBankDistinguishable_iff_exists_not_gap_dvd
#check Circle.Applications.ropePhaseBankDistinguishable_of_period_ge_context
#check Circle.Applications.ropeCollisionPairCountAtGap
#check Circle.Applications.ropeCollisionPairCountAtGap_pos_iff
#check Circle.Applications.ropePhaseBankCollision_at_gap_of_forall_dvd
#check Circle.Applications.ropeRealPhaseGap
#check Circle.Applications.ropeRealPhaseGapAbs
#check Circle.Applications.ropeRealPhaseNatTurnError
#check Circle.Applications.ropeRealPhaseIntTurnError
#check Circle.Applications.ropeRealPhaseGapAbs_eq_natGap_mul_abs
#check Circle.Applications.ropeRealPhaseGapAbs_ge_minGap_mul_lower
#check Circle.Applications.ropeRealPhaseNatTurnEndpointErrors_ge_margin_of_one_turn_window
#check Circle.Applications.ropeRealPhaseNatTurnError_ge_margin_of_one_turn_window
#check Circle.Applications.ropeRealPhaseIntTurnError_ge_margin_of_one_turn_window

end Circle.PaperAI04
