from __future__ import annotations

import shutil
import subprocess
import sys
from pathlib import Path
from typing import Any

import yaml

from repo_paths import ROOT


PROVED_STATUSES = {"proved", "lean_proved"}


def iter_manifest_yaml() -> list[Path]:
    return sorted(path for path in (ROOT / "manifests").rglob("*.yaml") if path.is_file())


def walk_yaml(value: Any, source: Path) -> list[dict[str, str]]:
    found: list[dict[str, str]] = []
    if isinstance(value, dict):
        status = value.get("status")
        lean_name = value.get("lean_name")
        if status in PROVED_STATUSES and lean_name:
            found.append(
                {
                    "id": str(value.get("id", "<missing id>")),
                    "lean_name": str(lean_name),
                    "source": str(source.relative_to(ROOT)),
                }
            )
        for child in value.values():
            found.extend(walk_yaml(child, source))
    elif isinstance(value, list):
        for child in value:
            found.extend(walk_yaml(child, source))
    return found


def proved_manifest_lean_names() -> list[dict[str, str]]:
    entries: list[dict[str, str]] = []
    for path in iter_manifest_yaml():
        data = yaml.safe_load(path.read_text())
        entries.extend(walk_yaml(data, path))

    unique: dict[str, dict[str, str]] = {}
    for entry in entries:
        unique.setdefault(entry["lean_name"], entry)
    return sorted(unique.values(), key=lambda item: item["lean_name"])


def lake_command() -> str:
    return shutil.which("lake") or str(Path.home() / ".elan" / "bin" / "lake")


def main() -> int:
    entries = proved_manifest_lean_names()
    if not entries:
        print("manifest Lean-name check failed: no proved Lean names found", file=sys.stderr)
        return 1

    check_file = ROOT / ".tools" / "manifest_lean_name_check.lean"
    check_file.parent.mkdir(parents=True, exist_ok=True)
    lines = [
        "import Circle",
        "",
        "/- Generated by scripts/check_manifest_lean_names.py. Do not edit. -/",
    ]
    lines.extend(f"#check {entry['lean_name']}" for entry in entries)
    check_file.write_text("\n".join(lines) + "\n")

    result = subprocess.run(
        [lake_command(), "env", "lean", str(check_file)],
        cwd=ROOT,
        text=True,
        capture_output=True,
    )
    try:
        check_file.unlink()
    except FileNotFoundError:
        pass

    if result.returncode != 0:
        combined = "\n".join(part for part in [result.stderr, result.stdout] if part)
        print("manifest Lean-name check failed:", file=sys.stderr)
        for line in combined.splitlines():
            if "error" in line.lower() or "unknown" in line.lower():
                print(line, file=sys.stderr)
        if not combined:
            print(f"lake env lean exited with {result.returncode}", file=sys.stderr)
        return result.returncode

    print(f"manifest Lean names ok: {len(entries)} proved declarations")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
